### ISSUE TITLE
Server Side Rendering, howto ?

### ISSUE THREAD

**Issue by brikou** [foxhound87/mobx-ajv-form#262] opened 2017-04-22 17:06 UTC
Do you have any advices dealing with SSR?

**Comment by foxhound87** [comment] 2017-04-24 09:47
Hello @brikou 

The SSR has many aspects to be considered and it depends on how your app is structured.

You can find some examples on the [RFX Stack](https://github.com/foxhound87/rfx-stack/tree/master/src/shared/forms), If your app is ok you should not have particular issues.

If you hit specific issues, elaborate them and I will glad to help you.

**Comment by brikou** [comment] 2017-04-24 09:49
Thanks for your reply, I'll take a look :)

**Comment by foxhound87** [comment] 2017-04-26 18:44
I'm closing this issue for now, feel free to reopen.

**Closed as completed by foxhound87** 2017-04-26 18:44 UTC
Labels: help wanted

**Comment by SimeonC** [comment] 2017-06-23 01:29
Hi @foxhound87. I've found an issue with server rendering (isomorphic) in my app - it's caused by the following line: https://github.com/foxhound87/mobx-react-form/blob/c8b5f9c44ffbb6a899611a2e901655fd307ae228/src/utils.js#L135.

The issue is that the server ID keeps incrementing on subsequent renders but the client restarts at 1 so I get errors similar to this:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) el for="firstName--1" class="" data-reac
 (server) el for="firstName--109" class="" data-re
```

This issue was solved in a roundabout way by this person: https://www.npmjs.com/package/react-uniqueid.
There is also a thread on official React about it: https://github.com/facebook/react/issues/5867

I think the simplest way of solving this would be to giving the option to override the uniqueId function. I can try put together a PR if that would be ok? Example override implementation: `form = new MobXReactForm({ fields }, { plugins, options: { uniqueId: () => Math.random() } });`

**Comment by foxhound87** [comment] 2017-06-23 11:06
Hello @SimeonC 

I tested this on the rfx-stack and next.js too and it's working well for me. I noticed that it occurs when you create the form instance inside the components instead of the mobx store. Where are you creating it?

**Comment by SimeonC** [comment] 2017-06-26 01:14
@foxhound87 Sorry for late reply - couldn't look at it over the weekend. I can replicate it on the rfx-stack demo (cloned from the master branch). I am instantiating my form in the mobx store before I call the first render.

1. Run `npm run web:dev`
2. Open `http://localhost:3000/auth`
3. Refresh the page, you should see the error in the console.

**Comment by foxhound87** [comment] 2017-06-26 13:42
You are right, I used to istantiate the Form outside the hydrated stores. I will try react-uniqueid and provide a custom function as you suggested, thank you!

**Comment by SimeonC** [comment] 2017-06-27 04:06
Cool, Let me know if you need/want any help!

**Comment by foxhound87** [comment] 2017-09-01 10:51
In version 1.32 the Form has the `uniqueId` option, you can define a function that takes the field instance as input.

Example:
https://github.com/foxhound87/mobx-react-form/blob/0f804601ada2a4d10ed32237ed63ffbe9feac052/src/utils.js#L141-L142

**Comment by chocholand** [comment] 2017-09-14 11:20
@foxhound87 I'm building with ssr. how to use uniqueId?
```
new MobxReactForm({ ...login }, { name: 'Login', options: { uniqueId: () => Math.random() }  })
```
I still have the problem.
Instead, figure out why the markup being generated is different on the client or server:
(client)  type="email" id="0.4456513283638319" na
 (server)  type="email" id="0.9525385504937858" na

**Comment by chocholand** [comment] 2017-09-14 11:37
I solved this.
```
let idCounter = (typeof window !== 'undefined' && window.__ID__) || 0;

function id() {
  return ++idCounter;
}

export const loginForm = new MobxReactForm({ ...login }, { name: 'Login', options: { uniqueId: () => id() } })
```

**Comment by LennardWesterveld** [comment] 2017-11-19 17:42
I think i need to reopen this issue because of the uniqueId i think there is a issue with it with SSR.
I installed mobx-react-form in my server side rendering react app and the id's are incrementing every time when i refresh the page. That means when i got lot of visitors that i end up in the 10.000 number and break my website after a long period of time.

Do any one know how to solve this problem? maybe use random? or a flush function that we can execute after react fully renderd en start for the next visitor by 0.

**Comment by foxhound87** [comment] 2018-01-10 17:59
@LennardWesterveld Sorry, I saw your message only now, can you create a repo with your code which replicates your issue? thanks.
